### ISSUE TITLE
multi-exponentiation

### ISSUE THREAD

**Issue by Sladuca** [filecoin-project/blstrs#28]
I'm using this crate for an implementation of KZG polynomial commitments, and creating a witness requires computing a "sum of products" of the form `elem[0] * scalar[0] + ... + elem[n-1] * scalar[n-1]`, which is slow for large degrees.

`blst` has a fast (4-5x faster than naive on my MB Pro 16 for 1000 elements) implementation of peppinger multiexponentiation in [`blst_p1s_mult_pippenger`](https://docs.rs/blst/0.3.6/blst/fn.blst_p1s_mult_pippenger.html). Would y'all be open to adding a `multi_exp` associated function to `G1Projective` and `G2Projective` for this?

I have an implementation [here](https://github.com/Sladuca/blstrs/blob/ff6712a5b0338aa312e2f9f008041209f5f9f1f3/src/g1.rs#L627) at https://github.com/Sladuca/blstrs/tree/multiexponentiation, but wanted to raise this for discussion anyways.

KZG commitments probably aren't the only applications that would benefit from this. Off the top of my head, Pederson commitments would too.

**Comment by davidrusu** [comment]
This would be useful to me as well, @Sladuca would you mind opening a PR? Perhaps the blstrs team will have more comments on the code?

**Comment by dot-asm** [comment]
I find it unfortunate that one has to opt for cloning data on blst interface. I'd even argue that it would be beneficial if blstrs types didn't require unsafe casts/transmutations. But apart from this last thing. It should be noted that blst has a dedicated set of arithmetic operations on scalars, and the question is if there are any obstacles to harmonization of the scalar types(*)? I mean so that it at least doesn't require cloning. [Naturally, this is a question rather to blstrs maintainers, not to the original poster. So one might argue that it's wrong spot to pose the question.]

Another question. The expectation was that the bulk conversion to affine coordinates wouldn't be something one does on a per-call basis. I mean one would customarily reuse the p1_affines vector. Is this assumption wrong? If so, then one can make a case for parallelization of the conversion. Either way, the interface is effectively incomplete and there is room for suggestions. For example, should there be a way to offload the affine point set to permanent storage? If so, would it be appropriate to use raw platform-specific data, or would it be appropriate to convert it to platform-neutral format?

BTW, Pippenger is an actual person, hence in writing it's more appropriate to refer to the algorithm in question as "Pippenger" rather than "pippenger" ;-)

(*) Just in case, no, I still don't see a reason to go beyond practical minimum required for actual applications.

**Comment by dignifiedquire** [comment]
@Sladuca please open a PR to blstrs directly. It should be easy to add based on your code, without any changes to blst.

@dot-asm regarding the unsafe casts, it is unfortunate, but guranteed to be safe in the latest version, as I enforce using `repr[transparent]` that all `blstrs` types are actually just empty wrappers around the `blst` types.

**Comment by dot-asm** [comment]
> unsafe casts ... guranteed to be safe in the latest version, as I enforce using repr[transparent] that all blstrs types are actually just empty wrappers around the blst types.

Yes, except for scalars. blstrs scalars are "aliased" to blst_fr, which can't be formally cast-ed to kind of scalars accepted by point multiplication subroutines. blst_fr is meant to denote Fr elements in Montgomery representation, which can't be used as point multiplicand. Montgomery representation should be used for big non-trivial operations like FFT/NTT(*), while applications that do point operations should be better off with a non-Montgomery type.

(*) Just in case, the original intention was that one would take a vector of scalars, convert it to Montgomery representation (in place if so desired), perform some big non-trivial operation, and convert it back from Montgomery representation (again, in place if so desired). Of course one can use to->do->from pattern for individual operations as well, but it would be more appropriate to internalize them in the library.

**Comment by dot-asm** [comment]
Just in case, it might be worth noting that point multiplication subroutines don't actually require scalars to be capped by `r`, the target group order. You can throw arbitrary long scalars at them and they will yield the correct results. In real-life applications it makes less sense, but purely formally `r` is not the "hard" limit for scalars. For example, naive cofactor clearing in G2 takes a 636-bit scalar and one can meaningfully use such a long scalar.

**Comment by Sladuca** [comment]
Hey! I somehow totally missed this thread and ended up not using it (KZG turned out to not be the best for our use case). I put up the PR in #37.

**Comment by dignifiedquire** [comment]
Thanks to @Sladuca for providing the PR, will be cutting a release shortly with this included
